// Code generated by github.com/varlink/go/cmd/varlink-go-interface-generator, DO NOT EDIT.

// com.openuc2.deviceadmin.openuc2 manages openUC2 OS-specific settings.
package comopenuc2deviceadminopenuc2

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/varlink/go/varlink"
)

// Generated type declarations

// The service was unable to perform the requested operation for an unspecified reason.
type Unknown struct {
	Description string `json:"description"`
}

func (e Unknown) Error() string {
	s := "com.openuc2.deviceadmin.openuc2.Unknown"
	s += fmt.Sprintf("(Description: %v)", e.Description)
	return s
}

func Dispatch_Error(err error) error {
	if e, ok := err.(*varlink.Error); ok {
		switch e.Name {
		case "com.openuc2.deviceadmin.openuc2.Unknown":
			errorRawParameters := e.Parameters.(*json.RawMessage)
			if errorRawParameters == nil {
				return e
			}
			var param Unknown
			err := json.Unmarshal(*errorRawParameters, &param)
			if err != nil {
				return e
			}
			return &param
		}
	}
	return err
}

// Generated client method calls

// UpdatePSKDropInFile updates the specified connection profile (as specified via file-based name,
// e.g. "wlan0-hotspot")'s Wi-Fi PSK drop-in snippet file (which is automatically determined)
// with the specified cleartext password.
// This operation does not try to regenerate the connection profile itself from the drop-in files.
type UpdatePSKDropInFile_methods struct{}

func UpdatePSKDropInFile() UpdatePSKDropInFile_methods { return UpdatePSKDropInFile_methods{} }

func (m UpdatePSKDropInFile_methods) Call(ctx context.Context, c *varlink.Connection, connProfile_in_ string, newPw_in_ string) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0, connProfile_in_, newPw_in_)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m UpdatePSKDropInFile_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, connProfile_in_ string, newPw_in_ string) (func(ctx context.Context) (uint64, error), error) {
	var in struct {
		ConnProfile string `json:"connProfile"`
		NewPw       string `json:"newPw"`
	}
	in.ConnProfile = connProfile_in_
	in.NewPw = newPw_in_
	receive, err := c.Send(ctx, "com.openuc2.deviceadmin.openuc2.UpdatePSKDropInFile", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m UpdatePSKDropInFile_methods) Upgrade(ctx context.Context, c *varlink.Connection, connProfile_in_ string, newPw_in_ string) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		ConnProfile string `json:"connProfile"`
		NewPw       string `json:"newPw"`
	}
	in.ConnProfile = connProfile_in_
	in.NewPw = newPw_in_
	receive, err := c.Upgrade(ctx, "com.openuc2.deviceadmin.openuc2.UpdatePSKDropInFile", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

// RegenerateConnProfile reassembles the file for the NetworkManager connection profile (specified by
// its file-based name, e.g. "wlan0-hotspot") from its constituent drop-in snippet files.
// This operation does not try to make NetworkManager reload the updated connection profile.
type RegenerateDropInConnProfile_methods struct{}

func RegenerateDropInConnProfile() RegenerateDropInConnProfile_methods {
	return RegenerateDropInConnProfile_methods{}
}

func (m RegenerateDropInConnProfile_methods) Call(ctx context.Context, c *varlink.Connection, connProfile_in_ string) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0, connProfile_in_)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m RegenerateDropInConnProfile_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, connProfile_in_ string) (func(ctx context.Context) (uint64, error), error) {
	var in struct {
		ConnProfile string `json:"connProfile"`
	}
	in.ConnProfile = connProfile_in_
	receive, err := c.Send(ctx, "com.openuc2.deviceadmin.openuc2.RegenerateDropInConnProfile", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m RegenerateDropInConnProfile_methods) Upgrade(ctx context.Context, c *varlink.Connection, connProfile_in_ string) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		ConnProfile string `json:"connProfile"`
	}
	in.ConnProfile = connProfile_in_
	receive, err := c.Upgrade(ctx, "com.openuc2.deviceadmin.openuc2.RegenerateDropInConnProfile", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

// Generated service interface with all methods

type comopenuc2deviceadminopenuc2Interface interface {
	UpdatePSKDropInFile(ctx context.Context, c VarlinkCall, connProfile_ string, newPw_ string) error
	RegenerateDropInConnProfile(ctx context.Context, c VarlinkCall, connProfile_ string) error
}

// Generated service object with all methods

type VarlinkCall struct{ varlink.Call }

// Generated reply methods for all varlink errors

// The service was unable to perform the requested operation for an unspecified reason.
func (c *VarlinkCall) ReplyUnknown(ctx context.Context, description_ string) error {
	var out Unknown
	out.Description = description_
	return c.ReplyError(ctx, "com.openuc2.deviceadmin.openuc2.Unknown", &out)
}

// Generated reply methods for all varlink methods

func (c *VarlinkCall) ReplyUpdatePSKDropInFile(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

func (c *VarlinkCall) ReplyRegenerateDropInConnProfile(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

// Generated dummy implementations for all varlink methods

// UpdatePSKDropInFile updates the specified connection profile (as specified via file-based name,
// e.g. "wlan0-hotspot")'s Wi-Fi PSK drop-in snippet file (which is automatically determined)
// with the specified cleartext password.
// This operation does not try to regenerate the connection profile itself from the drop-in files.
func (s *VarlinkInterface) UpdatePSKDropInFile(ctx context.Context, c VarlinkCall, connProfile_ string, newPw_ string) error {
	return c.ReplyMethodNotImplemented(ctx, "com.openuc2.deviceadmin.openuc2.UpdatePSKDropInFile")
}

// RegenerateConnProfile reassembles the file for the NetworkManager connection profile (specified by
// its file-based name, e.g. "wlan0-hotspot") from its constituent drop-in snippet files.
// This operation does not try to make NetworkManager reload the updated connection profile.
func (s *VarlinkInterface) RegenerateDropInConnProfile(ctx context.Context, c VarlinkCall, connProfile_ string) error {
	return c.ReplyMethodNotImplemented(ctx, "com.openuc2.deviceadmin.openuc2.RegenerateDropInConnProfile")
}

// Generated method call dispatcher

func (s *VarlinkInterface) VarlinkDispatch(ctx context.Context, call varlink.Call, methodname string) error {
	switch methodname {
	case "UpdatePSKDropInFile":
		var in struct {
			ConnProfile string `json:"connProfile"`
			NewPw       string `json:"newPw"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.comopenuc2deviceadminopenuc2Interface.UpdatePSKDropInFile(ctx, VarlinkCall{call}, in.ConnProfile, in.NewPw)

	case "RegenerateDropInConnProfile":
		var in struct {
			ConnProfile string `json:"connProfile"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.comopenuc2deviceadminopenuc2Interface.RegenerateDropInConnProfile(ctx, VarlinkCall{call}, in.ConnProfile)

	default:
		return call.ReplyMethodNotFound(ctx, methodname)
	}
}

// Generated varlink interface name

func (s *VarlinkInterface) VarlinkGetName() string {
	return `com.openuc2.deviceadmin.openuc2`
}

// Generated varlink interface description

func (s *VarlinkInterface) VarlinkGetDescription() string {
	return `# com.openuc2.deviceadmin.openuc2 manages openUC2 OS-specific settings.
interface com.openuc2.deviceadmin.openuc2

# The service was unable to perform the requested operation for an unspecified reason.
error Unknown (description: string)

# NetworkManager

# UpdatePSKDropInFile updates the specified connection profile (as specified via file-based name,
# e.g. "wlan0-hotspot")'s Wi-Fi PSK drop-in snippet file (which is automatically determined)
# with the specified cleartext password.
# This operation does not try to regenerate the connection profile itself from the drop-in files.
method UpdatePSKDropInFile(connProfile: string, newPw: string) -> ()

# RegenerateConnProfile reassembles the file for the NetworkManager connection profile (specified by
# its file-based name, e.g. "wlan0-hotspot") from its constituent drop-in snippet files.
# This operation does not try to make NetworkManager reload the updated connection profile.
method RegenerateDropInConnProfile(connProfile: string) -> ()
`
}

// Generated service interface

type VarlinkInterface struct {
	comopenuc2deviceadminopenuc2Interface
}

func VarlinkNew(m comopenuc2deviceadminopenuc2Interface) *VarlinkInterface {
	return &VarlinkInterface{m}
}
