// Code generated by github.com/varlink/go/cmd/varlink-go-interface-generator, DO NOT EDIT.

// com.openuc2.deviceadmin.openuc2 manages openUC2 OS-specific settings.
package comopenuc2deviceadminopenuc2

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/varlink/go/varlink"
)

// Generated type declarations

// The service was unable to perform the requested operation for an unspecified reason.
type Unknown struct {
	Description string `json:"description"`
}

func (e Unknown) Error() string {
	s := "com.openuc2.deviceadmin.openuc2.Unknown"
	s += fmt.Sprintf("(Description: %v)", e.Description)
	return s
}

func Dispatch_Error(err error) error {
	if e, ok := err.(*varlink.Error); ok {
		switch e.Name {
		case "com.openuc2.deviceadmin.openuc2.Unknown":
			errorRawParameters := e.Parameters.(*json.RawMessage)
			if errorRawParameters == nil {
				return e
			}
			var param Unknown
			err := json.Unmarshal(*errorRawParameters, &param)
			if err != nil {
				return e
			}
			return &param
		}
	}
	return err
}

// Generated client method calls

// SetWifiHotspotPassword changes the password (declared in the password snippet file located at the
// specified path) for the Wi-Fi hotspot defined by the specified connection profile and then updates
// the NetworkManager connection profile for the hotspot. This operation does not start/restart the
// hotspot unless 1) the Wi-Fi module is idle and able to make the hotspot, and 2) the hotspot is
// allowed to be started automatically.
type SetWifiHotspotPassword_methods struct{}

func SetWifiHotspotPassword() SetWifiHotspotPassword_methods { return SetWifiHotspotPassword_methods{} }

func (m SetWifiHotspotPassword_methods) Call(ctx context.Context, c *varlink.Connection, connProfile_in_ string, pwFile_in_ string, newPw_in_ string) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0, connProfile_in_, pwFile_in_, newPw_in_)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m SetWifiHotspotPassword_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, connProfile_in_ string, pwFile_in_ string, newPw_in_ string) (func(ctx context.Context) (uint64, error), error) {
	var in struct {
		ConnProfile string `json:"connProfile"`
		PwFile      string `json:"pwFile"`
		NewPw       string `json:"newPw"`
	}
	in.ConnProfile = connProfile_in_
	in.PwFile = pwFile_in_
	in.NewPw = newPw_in_
	receive, err := c.Send(ctx, "com.openuc2.deviceadmin.openuc2.SetWifiHotspotPassword", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m SetWifiHotspotPassword_methods) Upgrade(ctx context.Context, c *varlink.Connection, connProfile_in_ string, pwFile_in_ string, newPw_in_ string) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		ConnProfile string `json:"connProfile"`
		PwFile      string `json:"pwFile"`
		NewPw       string `json:"newPw"`
	}
	in.ConnProfile = connProfile_in_
	in.PwFile = pwFile_in_
	in.NewPw = newPw_in_
	receive, err := c.Upgrade(ctx, "com.openuc2.deviceadmin.openuc2.SetWifiHotspotPassword", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

// Generated service interface with all methods

type comopenuc2deviceadminopenuc2Interface interface {
	SetWifiHotspotPassword(ctx context.Context, c VarlinkCall, connProfile_ string, pwFile_ string, newPw_ string) error
}

// Generated service object with all methods

type VarlinkCall struct{ varlink.Call }

// Generated reply methods for all varlink errors

// The service was unable to perform the requested operation for an unspecified reason.
func (c *VarlinkCall) ReplyUnknown(ctx context.Context, description_ string) error {
	var out Unknown
	out.Description = description_
	return c.ReplyError(ctx, "com.openuc2.deviceadmin.openuc2.Unknown", &out)
}

// Generated reply methods for all varlink methods

func (c *VarlinkCall) ReplySetWifiHotspotPassword(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

// Generated dummy implementations for all varlink methods

// SetWifiHotspotPassword changes the password (declared in the password snippet file located at the
// specified path) for the Wi-Fi hotspot defined by the specified connection profile and then updates
// the NetworkManager connection profile for the hotspot. This operation does not start/restart the
// hotspot unless 1) the Wi-Fi module is idle and able to make the hotspot, and 2) the hotspot is
// allowed to be started automatically.
func (s *VarlinkInterface) SetWifiHotspotPassword(ctx context.Context, c VarlinkCall, connProfile_ string, pwFile_ string, newPw_ string) error {
	return c.ReplyMethodNotImplemented(ctx, "com.openuc2.deviceadmin.openuc2.SetWifiHotspotPassword")
}

// Generated method call dispatcher

func (s *VarlinkInterface) VarlinkDispatch(ctx context.Context, call varlink.Call, methodname string) error {
	switch methodname {
	case "SetWifiHotspotPassword":
		var in struct {
			ConnProfile string `json:"connProfile"`
			PwFile      string `json:"pwFile"`
			NewPw       string `json:"newPw"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.comopenuc2deviceadminopenuc2Interface.SetWifiHotspotPassword(ctx, VarlinkCall{call}, in.ConnProfile, in.PwFile, in.NewPw)

	default:
		return call.ReplyMethodNotFound(ctx, methodname)
	}
}

// Generated varlink interface name

func (s *VarlinkInterface) VarlinkGetName() string {
	return `com.openuc2.deviceadmin.openuc2`
}

// Generated varlink interface description

func (s *VarlinkInterface) VarlinkGetDescription() string {
	return `# com.openuc2.deviceadmin.openuc2 manages openUC2 OS-specific settings.
interface com.openuc2.deviceadmin.openuc2

# SetWifiHotspotPassword changes the password (declared in the password snippet file located at the
# specified path) for the Wi-Fi hotspot defined by the specified connection profile and then updates
# the NetworkManager connection profile for the hotspot. This operation does not start/restart the
# hotspot unless 1) the Wi-Fi module is idle and able to make the hotspot, and 2) the hotspot is
# allowed to be started automatically.
method SetWifiHotspotPassword(connProfile: string, pwFile: string, newPw: string) -> ()

# The service was unable to perform the requested operation for an unspecified reason.
error Unknown (description: string)
`
}

// Generated service interface

type VarlinkInterface struct {
	comopenuc2deviceadminopenuc2Interface
}

func VarlinkNew(m comopenuc2deviceadminopenuc2Interface) *VarlinkInterface {
	return &VarlinkInterface{m}
}
