// Code generated by github.com/varlink/go/cmd/varlink-go-interface-generator, DO NOT EDIT.

// com.openuc2.deviceadmin.networkmanager manages NetworkManager.
package comopenuc2deviceadminnetworkmanager

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/varlink/go/varlink"
)

// Generated type declarations

// The service was unable to perform the requested operation for an unspecified reason.
type Unknown struct {
	Description string `json:"description"`
}

func (e Unknown) Error() string {
	s := "com.openuc2.deviceadmin.networkmanager.Unknown"
	s += fmt.Sprintf("(Description: %v)", e.Description)
	return s
}

func Dispatch_Error(err error) error {
	if e, ok := err.(*varlink.Error); ok {
		switch e.Name {
		case "com.openuc2.deviceadmin.networkmanager.Unknown":
			errorRawParameters := e.Parameters.(*json.RawMessage)
			if errorRawParameters == nil {
				return e
			}
			var param Unknown
			err := json.Unmarshal(*errorRawParameters, &param)
			if err != nil {
				return e
			}
			return &param
		}
	}
	return err
}

// Generated client method calls

// ReloadConnections reloads all network connection files from disk, including noticing any added or
// deleted connection files.
type ReloadConnections_methods struct{}

func ReloadConnections() ReloadConnections_methods { return ReloadConnections_methods{} }

func (m ReloadConnections_methods) Call(ctx context.Context, c *varlink.Connection) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m ReloadConnections_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64) (func(ctx context.Context) (uint64, error), error) {
	receive, err := c.Send(ctx, "com.openuc2.deviceadmin.networkmanager.ReloadConnections", nil, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m ReloadConnections_methods) Upgrade(ctx context.Context, c *varlink.Connection) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	receive, err := c.Upgrade(ctx, "com.openuc2.deviceadmin.networkmanager.ReloadConnections", nil)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

// Generated service interface with all methods

type comopenuc2deviceadminnetworkmanagerInterface interface {
	ReloadConnections(ctx context.Context, c VarlinkCall) error
}

// Generated service object with all methods

type VarlinkCall struct{ varlink.Call }

// Generated reply methods for all varlink errors

// The service was unable to perform the requested operation for an unspecified reason.
func (c *VarlinkCall) ReplyUnknown(ctx context.Context, description_ string) error {
	var out Unknown
	out.Description = description_
	return c.ReplyError(ctx, "com.openuc2.deviceadmin.networkmanager.Unknown", &out)
}

// Generated reply methods for all varlink methods

func (c *VarlinkCall) ReplyReloadConnections(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

// Generated dummy implementations for all varlink methods

// ReloadConnections reloads all network connection files from disk, including noticing any added or
// deleted connection files.
func (s *VarlinkInterface) ReloadConnections(ctx context.Context, c VarlinkCall) error {
	return c.ReplyMethodNotImplemented(ctx, "com.openuc2.deviceadmin.networkmanager.ReloadConnections")
}

// Generated method call dispatcher

func (s *VarlinkInterface) VarlinkDispatch(ctx context.Context, call varlink.Call, methodname string) error {
	switch methodname {
	case "ReloadConnections":
		return s.comopenuc2deviceadminnetworkmanagerInterface.ReloadConnections(ctx, VarlinkCall{call})

	default:
		return call.ReplyMethodNotFound(ctx, methodname)
	}
}

// Generated varlink interface name

func (s *VarlinkInterface) VarlinkGetName() string {
	return `com.openuc2.deviceadmin.networkmanager`
}

// Generated varlink interface description

func (s *VarlinkInterface) VarlinkGetDescription() string {
	return `# com.openuc2.deviceadmin.networkmanager manages NetworkManager.
interface com.openuc2.deviceadmin.networkmanager

# ReloadConnections reloads all network connection files from disk, including noticing any added or
# deleted connection files.
method ReloadConnections() -> ()

# The service was unable to perform the requested operation for an unspecified reason.
error Unknown (description: string)
`
}

// Generated service interface

type VarlinkInterface struct {
	comopenuc2deviceadminnetworkmanagerInterface
}

func VarlinkNew(m comopenuc2deviceadminnetworkmanagerInterface) *VarlinkInterface {
	return &VarlinkInterface{m}
}
