// Code generated by github.com/varlink/go/cmd/varlink-go-interface-generator, DO NOT EDIT.

// com.openuc2.deviceadmin.networkmanager manages NetworkManager.
package comopenuc2deviceadminnetworkmanager

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/varlink/go/varlink"
)

// Generated type declarations

// The uuid input provided was invalid.
type InvalidUUID struct {
	Description string `json:"description"`
}

func (e InvalidUUID) Error() string {
	s := "com.openuc2.deviceadmin.networkmanager.InvalidUUID"
	s += fmt.Sprintf("(Description: %v)", e.Description)
	return s
}

// The service was unable to perform the requested operation for an unspecified reason.
type Unknown struct {
	Description string `json:"description"`
}

func (e Unknown) Error() string {
	s := "com.openuc2.deviceadmin.networkmanager.Unknown"
	s += fmt.Sprintf("(Description: %v)", e.Description)
	return s
}

func Dispatch_Error(err error) error {
	if e, ok := err.(*varlink.Error); ok {
		switch e.Name {
		case "com.openuc2.deviceadmin.networkmanager.InvalidUUID":
			errorRawParameters := e.Parameters.(*json.RawMessage)
			if errorRawParameters == nil {
				return e
			}
			var param InvalidUUID
			err := json.Unmarshal(*errorRawParameters, &param)
			if err != nil {
				return e
			}
			return &param
		case "com.openuc2.deviceadmin.networkmanager.Unknown":
			errorRawParameters := e.Parameters.(*json.RawMessage)
			if errorRawParameters == nil {
				return e
			}
			var param Unknown
			err := json.Unmarshal(*errorRawParameters, &param)
			if err != nil {
				return e
			}
			return &param
		}
	}
	return err
}

// Generated client method calls

// ReloadConnProfiles reloads all connection profiles from disk, including noticing any added or
// deleted connection files.
type ReloadConnProfiles_methods struct{}

func ReloadConnProfiles() ReloadConnProfiles_methods { return ReloadConnProfiles_methods{} }

func (m ReloadConnProfiles_methods) Call(ctx context.Context, c *varlink.Connection) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m ReloadConnProfiles_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64) (func(ctx context.Context) (uint64, error), error) {
	receive, err := c.Send(ctx, "com.openuc2.deviceadmin.networkmanager.ReloadConnProfiles", nil, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m ReloadConnProfiles_methods) Upgrade(ctx context.Context, c *varlink.Connection) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	receive, err := c.Upgrade(ctx, "com.openuc2.deviceadmin.networkmanager.ReloadConnProfiles", nil)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

// ReloadConnProfile reloads the UUID-specified connection profile from disk.
type ReloadConnProfile_methods struct{}

func ReloadConnProfile() ReloadConnProfile_methods { return ReloadConnProfile_methods{} }

func (m ReloadConnProfile_methods) Call(ctx context.Context, c *varlink.Connection, uuid_in_ string) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0, uuid_in_)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m ReloadConnProfile_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64, uuid_in_ string) (func(ctx context.Context) (uint64, error), error) {
	var in struct {
		Uuid string `json:"uuid"`
	}
	in.Uuid = uuid_in_
	receive, err := c.Send(ctx, "com.openuc2.deviceadmin.networkmanager.ReloadConnProfile", in, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m ReloadConnProfile_methods) Upgrade(ctx context.Context, c *varlink.Connection, uuid_in_ string) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	var in struct {
		Uuid string `json:"uuid"`
	}
	in.Uuid = uuid_in_
	receive, err := c.Upgrade(ctx, "com.openuc2.deviceadmin.networkmanager.ReloadConnProfile", in)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

// Generated service interface with all methods

type comopenuc2deviceadminnetworkmanagerInterface interface {
	ReloadConnProfiles(ctx context.Context, c VarlinkCall) error
	ReloadConnProfile(ctx context.Context, c VarlinkCall, uuid_ string) error
}

// Generated service object with all methods

type VarlinkCall struct{ varlink.Call }

// Generated reply methods for all varlink errors

// The uuid input provided was invalid.
func (c *VarlinkCall) ReplyInvalidUUID(ctx context.Context, description_ string) error {
	var out InvalidUUID
	out.Description = description_
	return c.ReplyError(ctx, "com.openuc2.deviceadmin.networkmanager.InvalidUUID", &out)
}

// The service was unable to perform the requested operation for an unspecified reason.
func (c *VarlinkCall) ReplyUnknown(ctx context.Context, description_ string) error {
	var out Unknown
	out.Description = description_
	return c.ReplyError(ctx, "com.openuc2.deviceadmin.networkmanager.Unknown", &out)
}

// Generated reply methods for all varlink methods

func (c *VarlinkCall) ReplyReloadConnProfiles(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

func (c *VarlinkCall) ReplyReloadConnProfile(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

// Generated dummy implementations for all varlink methods

// ReloadConnProfiles reloads all connection profiles from disk, including noticing any added or
// deleted connection files.
func (s *VarlinkInterface) ReloadConnProfiles(ctx context.Context, c VarlinkCall) error {
	return c.ReplyMethodNotImplemented(ctx, "com.openuc2.deviceadmin.networkmanager.ReloadConnProfiles")
}

// ReloadConnProfile reloads the UUID-specified connection profile from disk.
func (s *VarlinkInterface) ReloadConnProfile(ctx context.Context, c VarlinkCall, uuid_ string) error {
	return c.ReplyMethodNotImplemented(ctx, "com.openuc2.deviceadmin.networkmanager.ReloadConnProfile")
}

// Generated method call dispatcher

func (s *VarlinkInterface) VarlinkDispatch(ctx context.Context, call varlink.Call, methodname string) error {
	switch methodname {
	case "ReloadConnProfiles":
		return s.comopenuc2deviceadminnetworkmanagerInterface.ReloadConnProfiles(ctx, VarlinkCall{call})

	case "ReloadConnProfile":
		var in struct {
			Uuid string `json:"uuid"`
		}
		err := call.GetParameters(&in)
		if err != nil {
			return call.ReplyInvalidParameter(ctx, "parameters")
		}
		return s.comopenuc2deviceadminnetworkmanagerInterface.ReloadConnProfile(ctx, VarlinkCall{call}, in.Uuid)

	default:
		return call.ReplyMethodNotFound(ctx, methodname)
	}
}

// Generated varlink interface name

func (s *VarlinkInterface) VarlinkGetName() string {
	return `com.openuc2.deviceadmin.networkmanager`
}

// Generated varlink interface description

func (s *VarlinkInterface) VarlinkGetDescription() string {
	return `# com.openuc2.deviceadmin.networkmanager manages NetworkManager.
interface com.openuc2.deviceadmin.networkmanager

# ReloadConnProfiles reloads all connection profiles from disk, including noticing any added or
# deleted connection files.
method ReloadConnProfiles() -> ()

# ReloadConnProfile reloads the UUID-specified connection profile from disk.
method ReloadConnProfile(uuid: string) -> ()

# The uuid input provided was invalid.
error InvalidUUID (description: string)

# The service was unable to perform the requested operation for an unspecified reason.
error Unknown (description: string)
`
}

// Generated service interface

type VarlinkInterface struct {
	comopenuc2deviceadminnetworkmanagerInterface
}

func VarlinkNew(m comopenuc2deviceadminnetworkmanagerInterface) *VarlinkInterface {
	return &VarlinkInterface{m}
}
