// Code generated by github.com/varlink/go/cmd/varlink-go-interface-generator, DO NOT EDIT.

// com.openuc2.deviceadmin.boot manages the boot state of the system.
package comopenuc2deviceadminboot

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/varlink/go/varlink"
)

// Generated type declarations

// The service was unable to perform the requested operation for an unspecified reason.
type Unknown struct {
	Description string `json:"description"`
}

func (e Unknown) Error() string {
	s := "com.openuc2.deviceadmin.boot.Unknown"
	s += fmt.Sprintf("(Description: %v)", e.Description)
	return s
}

func Dispatch_Error(err error) error {
	if e, ok := err.(*varlink.Error); ok {
		switch e.Name {
		case "com.openuc2.deviceadmin.boot.Unknown":
			errorRawParameters := e.Parameters.(*json.RawMessage)
			if errorRawParameters == nil {
				return e
			}
			var param Unknown
			err := json.Unmarshal(*errorRawParameters, &param)
			if err != nil {
				return e
			}
			return &param
		}
	}
	return err
}

// Generated client method calls

// Poweroff shuts down and powers off the system.
type Poweroff_methods struct{}

func Poweroff() Poweroff_methods { return Poweroff_methods{} }

func (m Poweroff_methods) Call(ctx context.Context, c *varlink.Connection) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m Poweroff_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64) (func(ctx context.Context) (uint64, error), error) {
	receive, err := c.Send(ctx, "com.openuc2.deviceadmin.boot.Poweroff", nil, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m Poweroff_methods) Upgrade(ctx context.Context, c *varlink.Connection) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	receive, err := c.Upgrade(ctx, "com.openuc2.deviceadmin.boot.Poweroff", nil)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

// Reboot shuts down and reboots the system.
type Reboot_methods struct{}

func Reboot() Reboot_methods { return Reboot_methods{} }

func (m Reboot_methods) Call(ctx context.Context, c *varlink.Connection) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m Reboot_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64) (func(ctx context.Context) (uint64, error), error) {
	receive, err := c.Send(ctx, "com.openuc2.deviceadmin.boot.Reboot", nil, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m Reboot_methods) Upgrade(ctx context.Context, c *varlink.Connection) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	receive, err := c.Upgrade(ctx, "com.openuc2.deviceadmin.boot.Reboot", nil)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

// SoftReboot shuts down and reboots userspace.
// This operation only reboots userspace, leaving the kernel running.
type SoftReboot_methods struct{}

func SoftReboot() SoftReboot_methods { return SoftReboot_methods{} }

func (m SoftReboot_methods) Call(ctx context.Context, c *varlink.Connection) (err_ error) {
	receive, err_ := m.Send(ctx, c, 0)
	if err_ != nil {
		return
	}
	_, err_ = receive(ctx)
	return
}

func (m SoftReboot_methods) Send(ctx context.Context, c *varlink.Connection, flags uint64) (func(ctx context.Context) (uint64, error), error) {
	receive, err := c.Send(ctx, "com.openuc2.deviceadmin.boot.SoftReboot", nil, flags)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, err error) {
		flags, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

func (m SoftReboot_methods) Upgrade(ctx context.Context, c *varlink.Connection) (func(ctx context.Context) (flags uint64, conn varlink.ReadWriterContext, err_ error), error) {
	receive, err := c.Upgrade(ctx, "com.openuc2.deviceadmin.boot.SoftReboot", nil)
	if err != nil {
		return nil, err
	}
	return func(context.Context) (flags uint64, conn varlink.ReadWriterContext, err error) {
		flags, conn, err = receive(ctx, nil)
		if err != nil {
			err = Dispatch_Error(err)
			return
		}
		return
	}, nil
}

// Generated service interface with all methods

type comopenuc2deviceadminbootInterface interface {
	Poweroff(ctx context.Context, c VarlinkCall) error
	Reboot(ctx context.Context, c VarlinkCall) error
	SoftReboot(ctx context.Context, c VarlinkCall) error
}

// Generated service object with all methods

type VarlinkCall struct{ varlink.Call }

// Generated reply methods for all varlink errors

// The service was unable to perform the requested operation for an unspecified reason.
func (c *VarlinkCall) ReplyUnknown(ctx context.Context, description_ string) error {
	var out Unknown
	out.Description = description_
	return c.ReplyError(ctx, "com.openuc2.deviceadmin.boot.Unknown", &out)
}

// Generated reply methods for all varlink methods

func (c *VarlinkCall) ReplyPoweroff(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

func (c *VarlinkCall) ReplyReboot(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

func (c *VarlinkCall) ReplySoftReboot(ctx context.Context) error {
	return c.Reply(ctx, nil)
}

// Generated dummy implementations for all varlink methods

// Poweroff shuts down and powers off the system.
func (s *VarlinkInterface) Poweroff(ctx context.Context, c VarlinkCall) error {
	return c.ReplyMethodNotImplemented(ctx, "com.openuc2.deviceadmin.boot.Poweroff")
}

// Reboot shuts down and reboots the system.
func (s *VarlinkInterface) Reboot(ctx context.Context, c VarlinkCall) error {
	return c.ReplyMethodNotImplemented(ctx, "com.openuc2.deviceadmin.boot.Reboot")
}

// SoftReboot shuts down and reboots userspace.
// This operation only reboots userspace, leaving the kernel running.
func (s *VarlinkInterface) SoftReboot(ctx context.Context, c VarlinkCall) error {
	return c.ReplyMethodNotImplemented(ctx, "com.openuc2.deviceadmin.boot.SoftReboot")
}

// Generated method call dispatcher

func (s *VarlinkInterface) VarlinkDispatch(ctx context.Context, call varlink.Call, methodname string) error {
	switch methodname {
	case "Poweroff":
		return s.comopenuc2deviceadminbootInterface.Poweroff(ctx, VarlinkCall{call})

	case "Reboot":
		return s.comopenuc2deviceadminbootInterface.Reboot(ctx, VarlinkCall{call})

	case "SoftReboot":
		return s.comopenuc2deviceadminbootInterface.SoftReboot(ctx, VarlinkCall{call})

	default:
		return call.ReplyMethodNotFound(ctx, methodname)
	}
}

// Generated varlink interface name

func (s *VarlinkInterface) VarlinkGetName() string {
	return `com.openuc2.deviceadmin.boot`
}

// Generated varlink interface description

func (s *VarlinkInterface) VarlinkGetDescription() string {
	return `# com.openuc2.deviceadmin.boot manages the boot state of the system.
interface com.openuc2.deviceadmin.boot

# Poweroff shuts down and powers off the system.
method Poweroff() -> ()

# Reboot shuts down and reboots the system.
method Reboot() -> ()

# SoftReboot shuts down and reboots userspace.
# This operation only reboots userspace, leaving the kernel running.
method SoftReboot() -> ()

# The service was unable to perform the requested operation for an unspecified reason.
error Unknown (description: string)
`
}

// Generated service interface

type VarlinkInterface struct {
	comopenuc2deviceadminbootInterface
}

func VarlinkNew(m comopenuc2deviceadminbootInterface) *VarlinkInterface {
	return &VarlinkInterface{m}
}
